[build]
  base = "github.com/Beviryon/ryonv.a"  
  publish = "." 
  command = "echo 'No build command needed for static HTML'"  

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
